const API='https://eghtxtxkmvpdaasyqgmb.supabase.co/functions/v1/whats-up-api';
let EVENTS=[],category='all';
const MONTH=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'];
const AUD={kids:'Kids/family',teens:'Teens',adults:'Adults',seniors:'55+',allages:'All ages',special:'Special audience'};
const esc=(v)=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
const cleanUrl=(v)=>{try{const u=new URL(String(v||''));return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({action,...payload}),cache:'no-store'});const j=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(j.error||`Request failed ${r.status}`);return j}
function localParts(iso){const d=new Date(iso);const dateParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Edmonton',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d);const timeParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Edmonton',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const a={},b={};dateParts.forEach(p=>a[p.type]=p.value);timeParts.forEach(p=>b[p.type]=p.value);return{date:`${a.year}-${a.month}-${a.day}`,time:`${b.hour}:${b.minute}`}}
function categoryKey(v){const x=(v||'community').toLowerCase();if(x.includes('art')||x.includes('music'))return'arts';if(x.includes('sport'))return'sports';if(x.includes('family'))return'family';if(x.includes('55')||x.includes('senior'))return'seniors';if(x.includes('night')||x.includes('league')||x.includes('social'))return'social';return'community'}
function timeLabel(v){if(!v)return'Time TBA';const [h,m]=v.split(':').map(Number);const d=new Date();d.setHours(h,m);return d.toLocaleTimeString('en-CA',{hour:'numeric',minute:'2-digit'})}
function calendarUrl(e){if(!e.s)return'';const date=e.d.replaceAll('-','');const start=`${date}T${e.s.replace(':','')}00`;const end=e.e?`${date}T${e.e.replace(':','')}00`:`${date}T235900`;return 'https://calendar.google.com/calendar/render?'+new URLSearchParams({action:'TEMPLATE',text:e.t,dates:`${start}/${end}`,details:e.x+(e.u?`\\n${e.u}`:''),location:e.v,ctz:'America/Edmonton'})}
function eventCard(e){const d=new Date(`${e.d}T12:00:00`);const cal=calendarUrl(e),url=cleanUrl(e.u);return `<article class="card"><div class="card-top"><div class="datebox"><small>${MONTH[d.getMonth()]}</small><b>${d.getDate()}</b></div><div><small class="muted">${esc(e.c||'Community')}</small><h3>${esc(e.t)}</h3><div class="meta">${e.e?`${timeLabel(e.s)}–${timeLabel(e.e)}`:timeLabel(e.s)} · ${esc(e.v||'Location TBA')}</div></div></div><div class="card-body"><p>${esc(e.x||'')}</p><div class="badges"><span class="badge">${esc(AUD[e.a]||e.a||'All ages')}</span>${e.free?'<span class="badge">Free</span>':''}<span class="badge">${esc(e.p||'See organizer')}</span></div><div class="actions">${cal?`<a class="cal" href="${cal}" target="_blank" rel="noopener noreferrer">+ Google Calendar</a>`:'<span>Timing incomplete</span>'}${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">Official source</a>`:'<span>Source on file</span>'}</div></div><div class="source-row"><span>Verified source</span>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">View ↗</a>`:'<span></span>'}</div></article>`}
function venueOptions(){const sel=document.getElementById('venue'),current=sel.value||'all';const vals=[...new Set(EVENTS.map(e=>e.v||'Location TBA'))].sort();sel.innerHTML='<option value="all">All venues</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');sel.value=vals.includes(current)?current:'all'}
function render(){const q=document.getElementById('q').value.toLowerCase(),aud=document.getElementById('aud').value,venue=document.getElementById('venue').value,group=document.getElementById('group').value;const list=EVENTS.filter(e=>{const ck=categoryKey(e.c);return(category==='all'||(category==='free'?e.free:ck===category))&&(aud==='all'||e.a===aud)&&(venue==='all'||e.v===venue)&&(!q||`${e.t} ${e.v} ${e.x}`.toLowerCase().includes(q))}).sort((a,b)=>(a.d+(a.s||'99:99')).localeCompare(b.d+(b.s||'99:99')));document.getElementById('summary').textContent=`Showing ${list.length} of ${EVENTS.length} current listings.`;const out=document.getElementById('list');if(!list.length){out.className='grid';out.innerHTML='<div class="empty">No events match those filters. Try clearing your search or choosing All.</div>';return}if(group==='none'){out.className='grid';out.innerHTML=list.map(eventCard).join('');return}const grouped={};list.forEach(e=>{const key=group==='venue'?e.v:group==='audience'?(AUD[e.a]||e.a):new Date(`${e.d}T12:00:00`).toLocaleDateString('en-CA',{weekday:'long',month:'long',day:'numeric'});(grouped[key]||(grouped[key]=[])).push(e)});out.className='';out.innerHTML=Object.entries(grouped).map(([k,items])=>`<section class="section"><h2>${esc(k)}</h2><div class="grid">${items.map(eventCard).join('')}</div></section>`).join('')}
async function loadEvents(){try{const j=await api('events');EVENTS=(j.events||[]).map(b=>{const st=localParts(b.starts_at),en=b.ends_at?localParts(b.ends_at):null;return{t:b.title,d:st.date,s:b.time_tba?null:st.time,e:en&&en.date===st.date?en.time:null,v:b.venue_name_raw||b.location_text||'Location TBA',c:b.category||'Community',a:(b.audience||'allages').toLowerCase(),p:b.price_text||(b.is_free?'Free':'See organizer'),x:b.description||'',u:b.official_url||b.ticket_url||'',free:!!b.is_free}});venueOptions();render();document.getElementById('refreshStatus').textContent=`${EVENTS.length} live listings · updated from monitored sources`;}catch(err){document.getElementById('summary').textContent='Could not load current listings.';document.getElementById('list').innerHTML='<div class="empty">The event list could not be loaded right now. Please refresh and try again.</div>';console.error(err)}}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');category=b.dataset.category;render()}));
['q','aud','venue','group'].forEach(id=>document.getElementById(id).addEventListener(id==='q'?'input':'change',render));
document.getElementById('eventForm').addEventListener('submit',async(ev)=>{ev.preventDefault();const form=ev.currentTarget,status=document.getElementById('submitStatus'),button=form.querySelector('button[type="submit"]');if(!form.reportValidity())return;button.disabled=true;status.textContent='Saving for review…';const f=new FormData(form);try{await api('submit',{title:f.get('title'),event_date:f.get('event_date'),start_time:f.get('start_time'),end_time:f.get('end_time'),venue:f.get('venue'),source_url:f.get('source_url'),price_text:f.get('price_text'),audience:f.get('audience'),submitter_name:f.get('submitter_name'),submitter_email:f.get('submitter_email'),description:f.get('description'),notes:f.get('description'),website:f.get('website'),is_free:/^free\b/i.test(String(f.get('price_text')||''))});form.reset();status.textContent='Submitted. Your event is in the private review queue.';}catch(err){status.textContent='Could not submit right now. Please try again.';console.error(err)}finally{button.disabled=false}});
loadEvents();