const API='https://eghtxtxkmvpdaasyqgmb.supabase.co/functions/v1/whats-up-api';
let ownerSession=sessionStorage.getItem('whatsUpOwnerSession')||'';
const esc=(v)=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({action,...payload,owner_session:ownerSession}),cache:'no-store'});const j=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok){const e=new Error(j.error||`Request failed ${r.status}`);e.code=j.code||'';e.status=r.status;throw e}return j}
const option=(v,c,l)=>`<option value="${esc(v)}"${v===(c||'')?' selected':''}>${esc(l||v)}</option>`;
function card(s){return `<article class="owner-card" data-id="${esc(s.id)}"><h3>${esc(s.title)}</h3><div class="owner-meta">Submitted ${esc(new Date(s.submitted_at).toLocaleString('en-CA'))} by ${esc(s.submitter_name||'Unknown')} · ${esc(s.submitter_email||'No email')}</div><div class="owner-grid"><label class="wide">Event name<input data-f="title" value="${esc(s.title)}"></label><label>Date<input data-f="event_date" type="date" value="${esc(s.event_date||'')}"></label><label>Start time<input data-f="start_time" type="time" value="${esc((s.start_time||'').slice(0,5))}"></label><label>End time<input data-f="end_time" type="time" value="${esc((s.end_time||'').slice(0,5))}"></label><label>Venue / location<input data-f="venue" value="${esc(s.venue_text||'')}"></label><label class="wide">Official / source link<input data-f="source_url" type="url" value="${esc(s.source_url||'')}"></label><label>Category<select data-f="category">${option('Community',s.category,'Community')}${option('Family',s.category,'Family')}${option('Arts & music',s.category,'Arts & music')}${option('Sports',s.category,'Sports')}${option('Nightlife & leagues',s.category,'Nightlife & leagues')}${option('55+',s.category,'55+')}</select></label><label>Audience<select data-f="audience">${option('allages',s.audience,'All ages')}${option('kids',s.audience,'Kids/family')}${option('teens',s.audience,'Teens')}${option('adults',s.audience,'Adults')}${option('seniors',s.audience,'55+')}${option('special',s.audience,'Special audience')}</select></label><label>Price<input data-f="price_text" value="${esc(s.price_text||'')}"></label><label><span>Free event</span><input data-f="is_free" type="checkbox" ${s.is_free?'checked':''}></label><label class="full">Description / notes<textarea data-f="description" rows="4">${esc(s.description||s.notes||'')}</textarea></label></div><div class="owner-actions"><button class="savebtn" data-action="save" type="button">Save edits</button><button class="approvebtn" data-action="approve" type="button">Approve & publish</button><button class="rejectbtn" data-action="reject" type="button">Reject</button></div></article>`}
function read(c){const f=n=>c.querySelector(`[data-f="${n}"]`);return{id:c.dataset.id,title:f('title').value,event_date:f('event_date').value,start_time:f('start_time').value,end_time:f('end_time').value,venue:f('venue').value,source_url:f('source_url').value,category:f('category').value,audience:f('audience').value,price_text:f('price_text').value,is_free:f('is_free').checked,description:f('description').value,notes:f('description').value}}
function setSignedIn(on){document.getElementById('loginPanel').hidden=on;document.getElementById('signedInPanel').hidden=!on;if(!on)document.getElementById('ownerList').innerHTML=''}
async function sendCode(){const status=document.getElementById('ownerStatus'),b=document.getElementById('sendCode'),rb=document.getElementById('resendCode');b.disabled=true;rb.disabled=true;status.textContent='Sending code…';try{await api('owner_send_code');document.getElementById('verifyStep').hidden=false;document.getElementById('sendStep').hidden=true;status.textContent='Code sent. Enter the 6-digit code from your text message.';document.getElementById('otpCode').focus()}catch(err){status.textContent=err.code==='SMS_NOT_CONFIGURED'?'SMS delivery is not configured yet.':'Could not send a code right now.';console.error(err)}finally{b.disabled=false;rb.disabled=false}}
async function verifyCode(){const status=document.getElementById('ownerStatus'),input=document.getElementById('otpCode'),otp=input.value.trim();if(!/^\d{6}$/.test(otp)){status.textContent='Enter the 6-digit code.';return}status.textContent='Verifying…';try{const j=await api('owner_verify_code',{otp});ownerSession=j.owner_session;sessionStorage.setItem('whatsUpOwnerSession',ownerSession);input.value='';setSignedIn(true);await load()}catch(err){status.textContent='That code is invalid or expired.';console.error(err)}}
async function load(){const status=document.getElementById('ownerStatus'),list=document.getElementById('ownerList');if(!ownerSession){setSignedIn(false);return}status.textContent='Loading pending submissions…';list.innerHTML='';try{const j=await api('admin_list');setSignedIn(true);list.innerHTML=(j.submissions||[]).map(card).join('')||'<div class="owner-card">No pending submissions.</div>';status.textContent=`${(j.submissions||[]).length} pending submission${(j.submissions||[]).length===1?'':'s'}.`;list.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>act(b.closest('.owner-card'),b.dataset.action)))}catch(err){if(err.status===401){sessionStorage.removeItem('whatsUpOwnerSession');ownerSession='';setSignedIn(false);status.textContent='Your Owner session expired. Send a new code.'}else status.textContent=`Could not load submissions: ${err.message}`}}
async function act(c,action){const status=document.getElementById('ownerStatus'),data=read(c);try{if(action==='reject'){if(!confirm('Reject this submission?'))return;await api('admin_reject',{id:data.id})}else if(action==='save'){await api('admin_save',data)}else{if(!data.title||!data.event_date){status.textContent='Event name and date are required before approval.';return}await api('admin_approve',data)}status.textContent=action==='approve'?'Approved and published.':action==='reject'?'Submission rejected.':'Edits saved.';await load()}catch(err){status.textContent=`Action failed: ${err.message}`}}
async function signOut(){try{if(ownerSession)await api('owner_logout')}catch{}sessionStorage.removeItem('whatsUpOwnerSession');ownerSession='';setSignedIn(false);document.getElementById('verifyStep').hidden=true;document.getElementById('sendStep').hidden=false;document.getElementById('ownerStatus').textContent='Signed out.'}
document.getElementById('sendCode').addEventListener('click',sendCode);document.getElementById('resendCode').addEventListener('click',sendCode);document.getElementById('verifyCode').addEventListener('click',verifyCode);document.getElementById('otpCode').addEventListener('keydown',e=>{if(e.key==='Enter')verifyCode()});document.getElementById('signOut').addEventListener('click',signOut);if(ownerSession)load();else setSignedIn(false);